[package]
name = "alegemaate-github-io"
version = "0.1.0"
edition = "2021"
description = "Rust personal site"
readme = "README.md"
repository = "https://github.com/alegemaate/alegemaate.github.io"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
