name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy Site"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: public
          single-commit: true
