name: Check PR

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "v0.20.1"

      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build
        run: trunk build

      - name: Run tests
        run: cargo test --verbose
